## 모듈 import

In [ ]:
from IPython.display import Image
import numpy as np
import pandas as pd

## 데이터 다운로드

In [ ]:
# 데이터셋 다운로드를 위한 패키지 설치
!pip install opendata-kr -q

In [ ]:
from opendata import dataset

In [ ]:
# 데이터셋 다운로드
dataset.download('서울시대중교통')
dataset.download('서울시주민등록인구')

## Excel

[도큐먼트](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html)

### Excel - 불러오기

Excel 데이터를 바로 읽어들일 수 있으며, `sheet_name`을 지정하면 해당 sheet를 가져옵니다.

[참고] `pd.read_excel()`로 엑셀 데이터 로드시 에러 발생한다면 `engine='openpyxl'`을 추가

In [ ]:
excel = pd.read_excel('data/seoul_transportation.xlsx', sheet_name='철도', engine='openpyxl')

In [ ]:
excel.head()

In [ ]:
excel = pd.read_excel('data/seoul_transportation.xlsx', sheet_name='버스', engine='openpyxl')
excel.head()

`sheet_name`을 None으로 지정하면, 모든 sheet를 가지고 옵니다.

가지고 올 때는 OrderedDict로 가져오며, `keys()`로 **시트명을 조회**할 수 있습니다.

In [ ]:
excel = pd.read_excel('data/seoul_transportation.xlsx', sheet_name=None, engine='openpyxl')
excel

`keys()`로 포함하고 있는 시트를 조회합니다.

In [ ]:
# 시트 조회
excel.keys()

In [ ]:
excel['철도'].head()

In [ ]:
excel['버스'].head()

### Excel - 저장하기

DataFrame을 Excel로 저장할 수 있으며, Excel로 저장시 **파일명**을 지정합니다.

- `index=False` 옵션은 가급적 꼭 지정하는 옵션입니다. 지정을 안하면 **index가 별도의 컬럼으로 저장**되게 됩니다.
- `sheet_name`을 지정하여, 저장할 시트의 이름을 변경할 수 있습니다.

In [ ]:
excel = pd.read_excel('data/seoul_transportation.xlsx', sheet_name='철도', engine='openpyxl')
excel.head()

별도의 시트명 지정 없이 저장

In [ ]:
excel.to_excel('sample.xlsx', index=True)

시트명을 **샘플**로 지정하여 저장

In [ ]:
excel.to_excel('sample1.xlsx', index=False, sheet_name='샘플')

## CSV (Comma Separated Values)

- 한 줄이 한 개의 행에 해당하며, 열 사이에는 **쉼표(,)를 넣어 구분**합니다.
- Excel보다는 훨씬 가볍고 **차지하는 용량이 적기 때문에 대부분의 파일데이터는 csv 형태**로 제공됩니다.

### CSV - 불러오기

In [ ]:
df = pd.read_csv('data/seoul_population.csv')

In [ ]:
df

### CSV - 저장하기

저장하는 방법은 excel과 유사합니다. 다만, csv파일 형식에는 `sheet_name` 옵션은 없습니다.

In [ ]:
df = pd.read_csv('data/seoul_population.csv')

`to_csv()`으로 csv 파일형식으로 저장할 수 있습니다.

In [ ]:
df.to_csv('sample.csv', index=False)

읽어들인 **Excel 파일도 Csv로 저장**할 수 있습니다.

In [ ]:
excel = pd.read_excel('data/seoul_transportation.xlsx', sheet_name='버스', engine='openpyxl')
excel.head()

In [ ]:
excel.to_csv('sample1.csv', index=False)

## 연습문제

아래 코드를 실행하여 실습에 필요한 데이터셋을 다운로드 받습니다.

In [ ]:
dataset.download('판다스입출력샘플')

- `sample`변수에 `data/file_sample.xlsx` 파일을 읽어서 로드합니다.
- 로드한 후 sheet를 모두 출력합니다.

In [ ]:
# 코드를 입력해 주세요

<p><strong>[출력 결과]</strong></p><pre>dict_keys(['2020년 01월', '2020년 02월', '2020년 03월', '2020년 04월', '2020년 05월', '2020년 06월', '2020년 07월', '2020년 08월', '2020년 09월', '2020년 10월', '2020년 11월', '2020년 12월'])</pre>

2020년 10월 시트를 `sample_202010`에 로드 합니다.

In [ ]:
# 코드를 입력해 주세요

<p><strong>[출력 결과]</strong></p><div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>지역</th>
      <th>GS칼텍스_셀프</th>
      <th>GS칼텍스_일반</th>
      <th>S-OIL_셀프</th>
      <th>S-OIL_일반</th>
      <th>SK에너지_셀프</th>
      <th>SK에너지_일반</th>
      <th>알뜰(ex)_셀프</th>
      <th>알뜰주유소_셀프</th>
      <th>알뜰주유소_일반</th>
      <th>자가상표_일반</th>
      <th>현대오일뱅크_셀프</th>
      <th>현대오일뱅크_일반</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>서울 강남구</td>
      <td>1443.440000</td>
      <td>1627.111111</td>
      <td>1420.760000</td>
      <td>1593.250</td>
      <td>1416.866250</td>
      <td>1734.166667</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1385.230000</td>
      <td>1525.705000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>서울 강동구</td>
      <td>1413.275000</td>
      <td>1430.353333</td>
      <td>1418.970000</td>
      <td>1498.000</td>
      <td>1445.000000</td>
      <td>1653.695000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1403.063333</td>
      <td>1424.340000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>서울 강북구</td>
      <td>1293.675000</td>
      <td>1313.190000</td>
      <td>1275.100000</td>
      <td>1325.710</td>
      <td>1329.690000</td>
      <td>1295.840000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1322.300000</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3</th>
      <td>서울 강서구</td>
      <td>1361.773333</td>
      <td>1385.840000</td>
      <td>1376.913333</td>
      <td>NaN</td>
      <td>1325.516667</td>
      <td>1433.664000</td>
      <td>NaN</td>
      <td>1273.11</td>
      <td>1264.06</td>
      <td>NaN</td>
      <td>1299.240000</td>
      <td>1362.530000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>서울 관악구</td>
      <td>1415.450000</td>
      <td>1429.970000</td>
      <td>NaN</td>
      <td>1397.015</td>
      <td>1411.840000</td>
      <td>1436.280000</td>
      <td>NaN</td>
      <td>1313.00</td>
      <td>1329.45</td>
      <td>NaN</td>
      <td>1392.550000</td>
      <td>1407.050000</td>
    </tr>
    <tr>
      <th>5</th>
      <td>서울 광진구</td>
      <td>NaN</td>
      <td>1360.394000</td>
      <td>1337.160000</td>
      <td>1344.970</td>
      <td>NaN</td>
      <td>1373.623333</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1309.19</td>
      <td>NaN</td>
      <td>1358.733333</td>
      <td>1337.940000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>서울 구로구</td>
      <td>1285.940000</td>
      <td>1511.173333</td>
      <td>1286.420000</td>
      <td>1393.832</td>
      <td>NaN</td>
      <td>1336.065000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1321.77</td>
      <td>NaN</td>
      <td>1314.235000</td>
      <td>1391.170000</td>
    </tr>
    <tr>
      <th>7</th>
      <td>서울 금천구</td>
      <td>1313.940000</td>
      <td>NaN</td>
      <td>1305.565000</td>
      <td>1287.580</td>
      <td>NaN</td>
      <td>1351.600000</td>
      <td>NaN</td>
      <td>1282.46</td>
      <td>1291.67</td>
      <td>NaN</td>
      <td>1313.035000</td>
      <td>1379.390000</td>
    </tr>
    <tr>
      <th>8</th>
      <td>서울 노원구</td>
      <td>1340.890000</td>
      <td>1421.850000</td>
      <td>1370.966667</td>
      <td>NaN</td>
      <td>1373.275000</td>
      <td>1398.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1431.435000</td>
    </tr>
    <tr>
      <th>9</th>
      <td>서울 도봉구</td>
      <td>1331.920000</td>
      <td>1327.320000</td>
      <td>1329.896000</td>
      <td>1557.000</td>
      <td>1291.470000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1345.106667</td>
      <td>1309.936667</td>
    </tr>
    <tr>
      <th>10</th>
      <td>서울 동대문구</td>
      <td>1305.485000</td>
      <td>1304.980000</td>
      <td>1296.390000</td>
      <td>1372.500</td>
      <td>1367.550000</td>
      <td>1383.838000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1329.100000</td>
      <td>1386.727500</td>
    </tr>
    <tr>
      <th>11</th>
      <td>서울 동작구</td>
      <td>1413.840000</td>
      <td>1345.275000</td>
      <td>NaN</td>
      <td>1358.030</td>
      <td>NaN</td>
      <td>1484.350000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1393.290000</td>
      <td>1388.840000</td>
    </tr>
    <tr>
      <th>12</th>
      <td>서울 마포구</td>
      <td>NaN</td>
      <td>1371.190000</td>
      <td>1408.970000</td>
      <td>1556.175</td>
      <td>NaN</td>
      <td>1493.846000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1453.000000</td>
      <td>1420.580000</td>
    </tr>
    <tr>
      <th>13</th>
      <td>서울 서대문구</td>
      <td>1357.690000</td>
      <td>1358.230000</td>
      <td>1351.905000</td>
      <td>1320.810</td>
      <td>1360.226667</td>
      <td>1352.713333</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1352.840000</td>
      <td>1357.805000</td>
    </tr>
    <tr>
      <th>14</th>
      <td>서울 서초구</td>
      <td>1391.770000</td>
      <td>1408.220000</td>
      <td>1388.463333</td>
      <td>1629.940</td>
      <td>1402.270000</td>
      <td>1590.833333</td>
      <td>1272.39</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1417.290000</td>
      <td>1468.968000</td>
    </tr>
    <tr>
      <th>15</th>
      <td>서울 성동구</td>
      <td>1361.450000</td>
      <td>1650.000000</td>
      <td>1312.230000</td>
      <td>1342.190</td>
      <td>1418.770000</td>
      <td>1471.978333</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1299.58</td>
      <td>1350.725000</td>
      <td>1572.695000</td>
    </tr>
    <tr>
      <th>16</th>
      <td>서울 성북구</td>
      <td>1299.240000</td>
      <td>1333.710000</td>
      <td>1301.643333</td>
      <td>1354.725</td>
      <td>1309.065000</td>
      <td>1407.230000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1263.84</td>
      <td>NaN</td>
      <td>1306.835000</td>
      <td>1353.160000</td>
    </tr>
    <tr>
      <th>17</th>
      <td>서울 송파구</td>
      <td>1364.285000</td>
      <td>1381.450000</td>
      <td>1356.130000</td>
      <td>1412.840</td>
      <td>1359.053333</td>
      <td>1431.812500</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1367.140000</td>
      <td>1378.280000</td>
    </tr>
    <tr>
      <th>18</th>
      <td>서울 양천구</td>
      <td>1312.826667</td>
      <td>1323.050000</td>
      <td>1269.060000</td>
      <td>NaN</td>
      <td>1333.678000</td>
      <td>1447.435000</td>
      <td>NaN</td>
      <td>1292.87</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1347.365000</td>
      <td>1401.385000</td>
    </tr>
    <tr>
      <th>19</th>
      <td>서울 영등포구</td>
      <td>1350.437500</td>
      <td>1580.468333</td>
      <td>1349.940000</td>
      <td>1345.000</td>
      <td>1338.742500</td>
      <td>1600.968333</td>
      <td>NaN</td>
      <td>1276.42</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1349.728000</td>
      <td>1494.000000</td>
    </tr>
    <tr>
      <th>20</th>
      <td>서울 용산구</td>
      <td>NaN</td>
      <td>1769.362500</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1885.408333</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1800.507500</td>
    </tr>
    <tr>
      <th>21</th>
      <td>서울 은평구</td>
      <td>1332.586000</td>
      <td>1341.520000</td>
      <td>1338.050000</td>
      <td>NaN</td>
      <td>1334.837500</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1418.00</td>
      <td>1314.870000</td>
      <td>1399.000000</td>
    </tr>
    <tr>
      <th>22</th>
      <td>서울 종로구</td>
      <td>NaN</td>
      <td>1989.000000</td>
      <td>NaN</td>
      <td>1459.000</td>
      <td>1425.000000</td>
      <td>1943.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1665.775000</td>
    </tr>
    <tr>
      <th>23</th>
      <td>서울 중구</td>
      <td>NaN</td>
      <td>2067.053333</td>
      <td>NaN</td>
      <td>1758.000</td>
      <td>NaN</td>
      <td>1945.522000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1401.87</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1618.000000</td>
    </tr>
    <tr>
      <th>24</th>
      <td>서울 중랑구</td>
      <td>1315.525000</td>
      <td>1305.710000</td>
      <td>1303.493333</td>
      <td>1359.885</td>
      <td>1347.587500</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1338.420000</td>
      <td>1291.190000</td>
    </tr>
  </tbody>
</table>
</div>

- `sample_202010`을 **2020-10-oil-price.csv**로 내보냅니다.
- index는 지정하지 않습니다.

In [ ]:
# 코드를 입력해 주세요